/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kendy_math_NativeBN */

#ifndef _Included_kendy_math_NativeBN
#define _Included_kendy_math_NativeBN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_kendy_math_NativeBN_BN_1new
  (JNIEnv *, jobject);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_cmp
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_kendy_math_NativeBN_BN_1cmp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_copy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1copy
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    putLongInt
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_putLongInt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    putULongInt
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_putULongInt
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_dec2bn
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kendy_math_NativeBN_BN_1dec2bn
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_hex2bn
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kendy_math_NativeBN_BN_1hex2bn
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_bin2bn
 * Signature: ([BIZJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1bin2bn
  (JNIEnv *, jobject, jbyteArray, jint, jboolean, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    litEndInts2bn
 * Signature: ([IIZJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_litEndInts2bn
  (JNIEnv *, jobject, jintArray, jint, jboolean, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    twosComp2bn
 * Signature: ([BIJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_twosComp2bn
  (JNIEnv *, jobject, jbyteArray, jint, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    longInt
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_kendy_math_NativeBN_longInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_bn2dec
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kendy_math_NativeBN_BN_1bn2dec
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_bn2hex
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kendy_math_NativeBN_BN_1bn2hex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_bn2bin
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_kendy_math_NativeBN_BN_1bn2bin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    bn2litEndInts
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_kendy_math_NativeBN_bn2litEndInts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    sign
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_kendy_math_NativeBN_sign
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_set_negative
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1set_1negative
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     kendy_math_NativeBN
 * Method:    bitLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_kendy_math_NativeBN_bitLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_is_bit_set
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_kendy_math_NativeBN_BN_1is_1bit_1set
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_shift
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1shift
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_add_word
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1add_1word
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_mul_word
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1mul_1word
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_mod_word
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_kendy_math_NativeBN_BN_1mod_1word
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_add
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1add
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_sub
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1sub
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_gcd
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1gcd
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_mul
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1mul
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1exp
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_div
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1div
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_nnmod
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1nnmod
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_mod_exp
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1mod_1exp
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_mod_inverse
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1mod_1inverse
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_generate_prime_ex
 * Signature: (JIZJJ)V
 */
JNIEXPORT void JNICALL Java_kendy_math_NativeBN_BN_1generate_1prime_1ex
  (JNIEnv *, jobject, jlong, jint, jboolean, jlong, jlong);

/*
 * Class:     kendy_math_NativeBN
 * Method:    BN_primality_test
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_kendy_math_NativeBN_BN_1primality_1test
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     kendy_math_NativeBN
 * Method:    getNativeFinalizer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_kendy_math_NativeBN_getNativeFinalizer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
